### ISSUE TITLE
How to make blocks appear

### ISSUE THREAD

**Issue by klopfer** [aolney/jupyterlab-blockly-python-extension#13]
Thanks for this work.  I have the most basic of issues.  How do I get the blocks to appear?  The extension seems to be installed correctly (it appears in the extension manager) and I'm using Jupyter Lab > 4.0.  But I don't seem to have a way to activate the blocks as seen in the video.  Is there some configuration change or companion installations I need?

**Comment by klopfer** [comment]
I found it now in the command palette.  ctrl/cmd shift-c for anyone looking for this in the future.

**Comment by aolney** [comment]
Sorry I somehow missed the notification for this. In JupyterLab 3.x, the interface changed so extensions are access from the command palette by default. You can turn on the "old behavior" using your configuration settings in JupyterLab
